### ISSUE TITLE
make failed --> if statements in bold need to be enclosed 

### ISSUE THREAD

**Issue by pFremont** [lidaof/methylQA#10]
gcc -O -g -Wall -Werror -Wformat -Wimplicit -Wreturn-type -Wuninitialized -Werror=unused-but-set-variable -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -Icuskent -Icussamtools -o generic.o -c generic.c
generic.c: In function 'genMeDIPTex':
generic.c:2785:13: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
             **if (covCnt[i] != 0)**
             ^~
generic.c:2787:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
                 fprintf(f2, "  %s, %i\n", cpglabel2[i], covCnt[i]);
                 ^~~~~~~
generic.c:2804:13: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
             **if (countCnt[i] != 0)**
             ^~
generic.c:2806:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
                 fprintf(f2, "  %s, %lli\n", cpglabel2[i], countCnt[i]);
                 ^~~~~~~

**Comment by lidaof** [comment]
Hi @pFremont , which gcc version are you using?
i cannot reproduce it but I guess maybe your gcc is newer, mine is gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by pFremont** [comment]
I am using gcc version 7.1.1.  After I enclosed these two if statements I was able to successfully build the tool.

**Comment by lidaof** [comment]
thanks for the feedback @pFremont , I will make the changes in next version.

**Comment by huangziyan11111** [comment]
Does that means we need to change the line "CFLAGS= -Wall -Werror -Wformat -Wimplicit -Wreturn-type -Wuninitialized -Werror=unused-but-set-variable" from makefile into "-Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized" ?

**Comment by lidaof** [comment]
Hi @huangziyan11111 that might make it work...that removed warnings as errors, but let me know if this doesn't work for you. thank you!

**Comment by huangziyan11111** [comment]
I changed this line into "CFLAGS= -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized", while it still has something wrong to make. I upload the log file, Could you help me to examine?
[make.log.txt](https://github.com/lidaof/methylQA/files/8587565/make.log.txt)
And my gcc version is: gcc version 8.3.1 20191121 (Red Hat 8.3.1-5)

**Comment by lidaof** [comment]
Hi @huangziyan11111 can you do a `git pull` of this repo and try again? the error seems comes from the customized kent source folder which should be also updated, please see this line:
https://github.com/lidaof/methylQA/blob/master/cuskent/makefile#L3

**Comment by huangziyan11111** [comment]
Thank you, it works. 😊
