### ISSUE TITLE
Downloads link broken?

### ISSUE THREAD

**Issue by ewels** [lidaof/methylQA#5]
Hi there,

I tried to download the support files from http://methylqa.sourceforge.net/install.php (`hg19` chromosome size file and CpG locations) but I get a 404 error? Looks like the https://cgs.wustl.edu/~dli/ is missing.

Is this permanent? Any chance the files could be put up somewhere else instead?

Many thanks,

Phil

**Comment by lidaof** [comment]
I am sorry for the inconvenience and really late reply. Our whole lab is moving to a new building and we are just done with moving. Seems our IT still are fixing that issue. I will keep contacting them and put the link online asap. At the sametime I would try to add some docs telling how to make those files. Thank you @ewels .

**Comment by ewels** [comment]
Ok great, thanks for the update!

**Comment by lidaof** [comment]
Really sorry for the delay @ewels, those links are fixed finally...

**Comment by ewels** [comment]
Great stuff, thanks!
