### ISSUE TITLE
Unable to install methylQA

### ISSUE THREAD

**Issue by daoyingiris** [lidaof/methylQA#8]
When I installed methylQA, encountered such a problem“memgfx.c:428:1: error: ‘mgPutDot’ is static but used in inline function ‘mixDot’ which is not static [-Werror]
 mgPutDot(img,x,y,MAKECOLOR_32(r,g,b));” 
Could you tell me I should how to solve this problem?

**Comment by lidaof** [comment]
hi @daoyingiris , which system are you using? Linux or MacOSX? thanks.

**Comment by daoyingiris** [comment]
Thanks for your reply. my system is Linux.

**Comment by lidaof** [comment]
no problem @daoyingiris.
Usually the compile works pretty well under Linux, would you mind try change the 3rd line of `cuskent/makefile` to:
`CFLAGS= `

basically remove those -W flags..

**Comment by daoyingiris** [comment]
Thank you very much, I have installed it successfully.

**Comment by lidaof** [comment]
Thanks, I am closing it. Please open a new issue if you get another question :)
