### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by 0xaf1f** [lidaof/methylQA#9]
we're installing methylQA on our cluster by user request, but it appears as though the release tags aren't being used anymore (installation instructions recommend installing the HEAD of the repository). It would help us keep the software up-to-date if there are actual releases. It would also assure us that we are not grabbing some intermediate, unfinished state of development.

**Comment by lidaof** [comment]
Hi @afif-elghraoui , my apology. I made a release tag for current code now.

**Comment by 0xaf1f** [comment]
Many thanks!
